##
## Unit Tests & Coverage
##
name: check
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [".", "x/dc", "x/media"]

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - uses: actions/checkout@v4

      - name: go build
        working-directory: ${{ matrix.module }}
        run: |
          go build ./...

      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          install-go: false
          working-directory: ${{ matrix.module }}
